services:
  app:
    build:
      context: ./eventus_core
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventus
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_DATA_REDIS_HOST: redis
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: eventus

  redis:
    image: redis:7.0-alpine         # 가벼운 Alpine 기반 Redis
    container_name: redis
    ports:
      - "6379:6379"                 # 호스트 6379 → 컨테이너 6379
    volumes:
      - redis-data:/data            # 데이터 영속화
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
    driver: local