spring:
  application:
    name: eventus_core
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/eventus
    username: root
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
  flyway:
    enabled: true
    locations: classpath:db/migration
    # 이미 테이블이 있는 DB에서 Flyway를 적용할 경우, Flyway가 기존 테이블을 "초기 상태"로 간주하도록 합니다.
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: eventus
  rabbitmq:
    host: localhost
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true